// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as CvSvg from "../../public/static/icons/cv.svg";
import * as FactSvg from "../../public/static/icons/fact.svg";
import * as HomeSvg from "../../public/static/icons/home.svg";
import * as MailSvg from "../../public/static/icons/mail.svg";
import * as GithubSvg from "../../public/static/icons/github.svg";
import * as ContactSvg from "../../public/static/icons/contact.svg";
import * as TwitterSvg from "../../public/static/icons/twitter.svg";
import * as LinkedinSvg from "../../public/static/icons/linkedin.svg";

var Style = /* module */[
  /* height */"1.0rem",
  /* width */"1.0rem"
];

var make = GithubSvg.default;

var Github = /* module */[/* make */make];

var make$1 = ContactSvg.default;

var Contact = /* module */[/* make */make$1];

var make$2 = HomeSvg.default;

var Home = /* module */[/* make */make$2];

var make$3 = CvSvg.default;

var Resume = /* module */[/* make */make$3];

var make$4 = FactSvg.default;

var Fact = /* module */[/* make */make$4];

var make$5 = LinkedinSvg.default;

var LinkedIn = /* module */[/* make */make$5];

var make$6 = TwitterSvg.default;

var Twitter = /* module */[/* make */make$6];

var make$7 = MailSvg.default;

var Mail = /* module */[/* make */make$7];

export {
  Style ,
  Github ,
  Contact ,
  Home ,
  Resume ,
  Fact ,
  LinkedIn ,
  Twitter ,
  Mail ,
  
}
/* make Not a pure module */
