// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Gallery(Props) {
  return React.createElement("div", undefined, "Gallery");
}

var make = Gallery;

var $$default = Gallery;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
