// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";

var galleryContainer = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.gridTemplateColumns(/* :: */[
              Css.fr(1.0),
              /* :: */[
                Css.fr(1.0),
                /* :: */[
                  Css.fr(1.0),
                  /* :: */[
                    Css.fr(1.0),
                    /* :: */[
                      Css.fr(1.0),
                      /* :: */[
                        Css.fr(1.0),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]),
        /* [] */0
      ]
    ]);

var galleryItem = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            100.0
          ]),
      /* :: */[
        Css.height(/* `percent */[
              -119887163,
              100.0
            ]),
        /* [] */0
      ]
    ]);

var Style = /* module */[
  /* galleryContainer */galleryContainer,
  /* galleryItem */galleryItem
];

var imagesToRender = /* array */[
  "img1.png",
  "img2.png",
  "img3.png",
  "img4.png",
  "img5.png",
  "img6.png",
  "img7.jpg",
  "img8.jpg",
  "img9.jpg",
  "img10.jpg",
  "img11.jpg",
  "img12.jpg"
];

function Gallery(Props) {
  return React.createElement("div", {
              className: galleryContainer
            }, $$Array.map((function (img) {
                    return React.createElement("figure", {
                                key: img
                              }, React.createElement("img", {
                                    className: galleryItem,
                                    src: "static/images/" + (String(img) + "")
                                  }));
                  }), imagesToRender));
}

var make = Gallery;

var $$default = Gallery;

export {
  Style ,
  imagesToRender ,
  make ,
  $$default ,
  $$default as default,
  
}
/* galleryContainer Not a pure module */
