// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Style$Website from "./Style.bs.js";

var iconSectionContainer = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.display(/* flex */-1010954439),
            /* :: */[
              Css.justifyContent(/* flexStart */662439529),
              /* :: */[
                Css.alignItems(/* start */67859554),
                /* [] */0
              ]
            ]
          ]),
      /* :: */[
        "container",
        /* [] */0
      ]
    ]);

var iconSectionTitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$Website.Sizes[/* medium */1]),
            /* [] */0
          ]),
      /* :: */[
        "title",
        /* [] */0
      ]
    ]);

var iconSectionIcon = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.justifySelf(/* center */98248149),
            /* :: */[
              Css.marginRight(/* `rem */[
                    5691738,
                    1.0
                  ]),
              /* [] */0
            ]
          ]),
      /* :: */[
        "icon",
        /* [] */0
      ]
    ]);

var Style = /* module */[
  /* iconSectionContainer */iconSectionContainer,
  /* iconSectionTitle */iconSectionTitle,
  /* iconSectionIcon */iconSectionIcon
];

function IconSection(Props) {
  var title = Props.title;
  var icon = Props.icon;
  var href = Props.href;
  var children = Props.children;
  return React.createElement("section", {
              className: "section is-fluid"
            }, React.createElement("a", {
                  href: href
                }, React.createElement("div", {
                      className: iconSectionContainer
                    }, React.createElement("span", {
                          className: iconSectionIcon
                        }, icon), React.createElement("h2", {
                          className: iconSectionTitle
                        }, title), children)));
}

var make = IconSection;

export {
  Style ,
  make ,
  
}
/* iconSectionContainer Not a pure module */
