// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Icons$MyBlog from "../../bindings/Icons.bs.js";
import * as Style$MyBlog from "./Style.bs.js";

var navBarBrand = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.display(/* flex */-1010954439),
            /* :: */[
              Css.flexDirection(/* column */-963948842),
              /* :: */[
                Css.justifyContent(/* start */67859554),
                /* :: */[
                  Css.alignContent(/* start */67859554),
                  /* :: */[
                    Css.paddingLeft(/* `rem */[
                          5691738,
                          2.0
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-brand",
        /* [] */0
      ]
    ]);

var navBarTitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* large */0]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "title",
          /* :: */[
            "is-marginless",
            /* :: */[
              "is-paddless",
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var navBarSubtitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* small */2]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "subtitle",
          /* [] */0
        ]
      ]
    ]);

var navBarMenu = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* small */2]),
            /* :: */[
              Css.paddingRight(Css.rem(2.0)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "navbar-menu",
        /* [] */0
      ]
    ]);

var navBarItem = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* small */2]),
            /* :: */[
              Css.fontWeight(/* bold */-1055161979),
              /* :: */[
                Css.paddingRight(Css.rem(2.0)),
                /* :: */[
                  Css.display(/* flex */-1010954439),
                  /* :: */[
                    Css.justifyContent(/* center */98248149),
                    /* :: */[
                      Css.alignItems(/* center */98248149),
                      /* :: */[
                        Css.color(Style$MyBlog.Colors[/* white */5]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-menu",
        /* [] */0
      ]
    ]);

var Style = /* module */[
  /* navBarBrand */navBarBrand,
  /* navBarTitle */navBarTitle,
  /* navBarSubtitle */navBarSubtitle,
  /* navBarMenu */navBarMenu,
  /* navBarItem */navBarItem
];

function Navbar(Props) {
  return React.createElement("nav", {
              "aria-label": "main navigation",
              className: "navbar is-primary",
              role: "navigation"
            }, React.createElement("div", {
                  className: navBarBrand
                }, React.createElement("h1", {
                      className: navBarTitle
                    }, "Martin Minkov"), React.createElement("h2", {
                      className: navBarSubtitle
                    }, "Software Developer from Vancouver, Canada")), React.createElement("div", {
                  className: navBarMenu
                }, React.createElement("div", {
                      className: "navbar-end"
                    }, React.createElement("a", {
                          className: navBarItem,
                          href: "/"
                        }, React.createElement("span", {
                              className: "icon"
                            }, React.createElement(Icons$MyBlog.Home[/* make */0], {
                                  height: "1.0rem"
                                })), React.createElement("span", undefined, "Home")), React.createElement("a", {
                          className: navBarItem
                        }, React.createElement("span", {
                              className: "icon"
                            }, React.createElement(Icons$MyBlog.Fact[/* make */0], {
                                  height: "1.0rem"
                                })), React.createElement("span", undefined, "Fun Facts")), React.createElement("a", {
                          className: navBarItem,
                          href: "https://github.com/martinminkov/"
                        }, React.createElement("span", {
                              className: "icon"
                            }, React.createElement(Icons$MyBlog.Github[/* make */0], {
                                  height: "1.0rem"
                                })), React.createElement("span", undefined, "Github")), React.createElement("a", {
                          className: navBarItem,
                          href: "/contact"
                        }, React.createElement("span", {
                              className: "icon"
                            }, React.createElement(Icons$MyBlog.Contact[/* make */0], {
                                  height: "1.0rem"
                                })), React.createElement("span", undefined, "Contact")))));
}

var make = Navbar;

var $$default = Navbar;

export {
  Style ,
  make ,
  $$default ,
  $$default as default,
  
}
/* navBarBrand Not a pure module */
