// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Style$MyBlog from "./Style.bs.js";

var navbarBrand = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.display(/* flex */-1010954439),
            /* :: */[
              Css.flexDirection(/* column */-963948842),
              /* :: */[
                Css.justifyContent(/* start */67859554),
                /* :: */[
                  Css.alignContent(/* start */67859554),
                  /* :: */[
                    Css.paddingLeft(Css.rem(2.0)),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-brand",
        /* [] */0
      ]
    ]);

var navbarTitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* large */0]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "title",
          /* :: */[
            "is-marginless",
            /* :: */[
              "is-paddless",
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var navbarSubtitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* small */2]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "subtitle",
          /* [] */0
        ]
      ]
    ]);

var navBarMenu = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$MyBlog.Sizes[/* small */2]),
            /* :: */[
              Css.paddingRight(Css.rem(2.0)),
              /* [] */0
            ]
          ]),
      /* :: */[
        "navbar-menu",
        /* [] */0
      ]
    ]);

var Style = /* module */[
  /* navbarBrand */navbarBrand,
  /* navbarTitle */navbarTitle,
  /* navbarSubtitle */navbarSubtitle,
  /* navBarMenu */navBarMenu
];

function Navbar(Props) {
  return React.createElement("nav", {
              "aria-label": "main navigation",
              className: "navbar is-light",
              role: "navigation"
            }, React.createElement("div", {
                  className: navbarBrand
                }, React.createElement("h1", {
                      className: navbarTitle
                    }, "Martin Minkov"), React.createElement("h2", {
                      className: navbarSubtitle
                    }, "Software Developer from Vancouver, Canada")), React.createElement("div", {
                  className: navBarMenu
                }, React.createElement("div", {
                      className: "navbar-end"
                    }, React.createElement("a", {
                          className: "navbar-item"
                        }, "Home"), React.createElement("a", {
                          className: "navbar-item"
                        }, "Fun Facts"), React.createElement("a", {
                          className: "navbar-item"
                        }, "Github"), React.createElement("a", {
                          className: "navbar-item"
                        }, "Contact"))));
}

var make = Navbar;

var $$default = Navbar;

export {
  Style ,
  make ,
  $$default ,
  $$default as default,
  
}
/* navbarBrand Not a pure module */
