// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Link from "next/link";
import * as Icons$Website from "../../bindings/Icons.bs.js";
import * as Style$Website from "./Style.bs.js";

var navBar = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.width(/* `percent */[
                  -119887163,
                  100.0
                ]),
            /* [] */0
          ]),
      /* :: */[
        "navbar",
        /* :: */[
          "is-primary",
          /* [] */0
        ]
      ]
    ]);

var navBarBrand = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.display(/* flex */-1010954439),
            /* :: */[
              Css.flexDirection(/* column */-963948842),
              /* :: */[
                Css.justifyContent(/* start */67859554),
                /* :: */[
                  Css.alignContent(/* start */67859554),
                  /* :: */[
                    Css.paddingLeft(/* `rem */[
                          5691738,
                          2.0
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-brand",
        /* [] */0
      ]
    ]);

var navBarTitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$Website.Sizes[/* large */0]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "title",
          /* :: */[
            "is-marginless",
            /* :: */[
              "is-paddless",
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

function navBarBurger(menuIsActive) {
  return Css.merge(/* :: */[
              menuIsActive ? "is-active" : "",
              /* :: */[
                "navbar-burger",
                /* :: */[
                  "burger",
                  /* [] */0
                ]
              ]
            ]);
}

var navBarSubtitle = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.fontSize(Style$Website.Sizes[/* small */2]),
            /* [] */0
          ]),
      /* :: */[
        "navbar-item",
        /* :: */[
          "subtitle",
          /* [] */0
        ]
      ]
    ]);

function navBarMenu(menuIsActive) {
  return Css.merge(/* :: */[
              Css.style(/* :: */[
                    Css.paddingTop(Css.px(0)),
                    /* :: */[
                      Css.fontSize(Style$Website.Sizes[/* small */2]),
                      /* :: */[
                        Css.paddingRight(Css.rem(2.0)),
                        /* [] */0
                      ]
                    ]
                  ]),
              /* :: */[
                menuIsActive ? "is-active" : "",
                /* :: */[
                  "navbar-menu",
                  /* [] */0
                ]
              ]
            ]);
}

var navBarItem = Css.merge(/* :: */[
      Css.style(/* :: */[
            Css.paddingRight(Css.rem(2.0)),
            /* :: */[
              Css.display(/* flex */-1010954439),
              /* :: */[
                Css.justifyContent(/* center */98248149),
                /* :: */[
                  Css.alignItems(/* center */98248149),
                  /* :: */[
                    Css.fontSize(Style$Website.Sizes[/* medium */1]),
                    /* :: */[
                      Css.letterSpacing(/* `px */[
                            25096,
                            1
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]),
      /* :: */[
        "navbar-item",
        /* [] */0
      ]
    ]);

function navBarLink(menuIsActive) {
  if (menuIsActive) {
    return Css.style(/* :: */[
                Css.fontWeight(/* semiBold */-812709613),
                /* :: */[
                  Css.color(Style$Website.Colors[/* black */6]),
                  /* :: */[
                    Css.paddingLeft(/* `rem */[
                          5691738,
                          1.0
                        ]),
                    /* [] */0
                  ]
                ]
              ]);
  } else {
    return Css.style(/* :: */[
                Css.fontWeight(/* semiBold */-812709613),
                /* :: */[
                  Css.color(Style$Website.Colors[/* white */5]),
                  /* :: */[
                    Css.paddingLeft(/* `rem */[
                          5691738,
                          1.0
                        ]),
                    /* [] */0
                  ]
                ]
              ]);
  }
}

var Style = /* module */[
  /* navBar */navBar,
  /* navBarBrand */navBarBrand,
  /* navBarTitle */navBarTitle,
  /* navBarBurger */navBarBurger,
  /* navBarSubtitle */navBarSubtitle,
  /* navBarMenu */navBarMenu,
  /* navBarItem */navBarItem,
  /* navBarLink */navBarLink
];

var initialState = /* record */[/* menuIsActive */false];

function reducer(state, action) {
  return /* record */[/* menuIsActive */!state[/* menuIsActive */0]];
}

function s(s$1) {
  return s$1;
}

function Navbar(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "hero-head"
            }, React.createElement("nav", {
                  className: navBar,
                  id: "topnav"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: navBarBrand
                        }, React.createElement(Link.default, {
                              href: "/",
                              children: React.createElement("h1", {
                                    className: navBarTitle
                                  }, "Martin Minkov")
                            }), React.createElement("h2", {
                              className: navBarSubtitle
                            }, "Software Developer from Vancouver, Canada"), React.createElement("span", {
                              className: navBarBurger(state[/* menuIsActive */0]),
                              onClick: (function (_event) {
                                  return Curry._1(dispatch, /* ToggleMenu */0);
                                })
                            }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                          className: navBarMenu(state[/* menuIsActive */0]),
                          id: "navbarMenu"
                        }, React.createElement("div", {
                              className: "navbar-end"
                            }, React.createElement("div", {
                                  className: navBarItem
                                }, React.createElement("span", {
                                      className: "icon"
                                    }, React.createElement(Icons$Website.Home[/* make */0], {
                                          height: "4.0rem"
                                        })), React.createElement(Link.default, {
                                      href: "/",
                                      children: React.createElement("a", {
                                            className: navBarLink(state[/* menuIsActive */0])
                                          }, "Home")
                                    })), React.createElement("div", {
                                  className: navBarItem
                                }, React.createElement("span", {
                                      className: "icon"
                                    }, React.createElement(Icons$Website.Fact[/* make */0], {
                                          height: "4.0rem"
                                        })), React.createElement(Link.default, {
                                      href: "/funfacts",
                                      children: React.createElement("a", {
                                            className: navBarLink(state[/* menuIsActive */0])
                                          }, "Fun Facts")
                                    })), React.createElement("div", {
                                  className: navBarItem
                                }, React.createElement("span", {
                                      className: "icon"
                                    }, React.createElement(Icons$Website.Github[/* make */0], {
                                          height: "4.0rem"
                                        })), React.createElement("a", {
                                      className: navBarLink(state[/* menuIsActive */0]),
                                      href: "https://github.com/martinminkov/"
                                    }, "Github")), React.createElement("div", {
                                  className: navBarItem
                                }, React.createElement("span", {
                                      className: "icon"
                                    }, React.createElement(Icons$Website.Contact[/* make */0], {
                                          height: "4.0rem"
                                        })), React.createElement(Link.default, {
                                      href: "/contact",
                                      children: React.createElement("a", {
                                            className: navBarLink(state[/* menuIsActive */0])
                                          }, "Contact")
                                    })))))));
}

var make = Navbar;

var $$default = Navbar;

export {
  Style ,
  initialState ,
  reducer ,
  s ,
  make ,
  $$default ,
  $$default as default,
  
}
/* navBar Not a pure module */
