// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var Colors_000 = /* darkGrey : `hex */[
  5194459,
  "455a64"
];

var Colors_001 = /* mediumGrey : `hex */[
  5194459,
  "607d8b"
];

var Colors_002 = /* lightGrey : `hex */[
  5194459,
  "cfd8dc"
];

var Colors_003 = /* white : `hex */[
  5194459,
  "ffffff"
];

var Colors = /* module */[
  Colors_000,
  Colors_001,
  Colors_002,
  Colors_003
];

var Sizes_000 = /* large : `rem */[
  5691738,
  1.8
];

var Sizes_001 = /* medium : `rem */[
  5691738,
  1.2
];

var Sizes_002 = /* small : `rem */[
  5691738,
  0.8
];

var Sizes = /* module */[
  Sizes_000,
  Sizes_001,
  Sizes_002
];

function defaults(param) {
  return /* tuple */[
          "html",
          /* :: */[
            Css.boxSizing(/* borderBox */9307263),
            /* :: */[
              Css.fontSize(Css.pct(62.5)),
              /* [] */0
            ]
          ]
        ];
}

var Control = /* module */[/* defaults */defaults];

export {
  Colors ,
  Sizes ,
  Control ,
  
}
/* Css Not a pure module */
