// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Style$Website from "../src/components/layout/Style.bs.js";
import * as Section$Website from "../src/components/layout/Section.bs.js";

var funFactText = Css.selector("p", /* :: */[
      Css.fontSize(Style$Website.Sizes[/* medium */1]),
      /* [] */0
    ]);

var titleContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(/* column */-963948842),
        /* :: */[
          Css.justifyContent(/* center */98248149),
          /* :: */[
            Css.alignItems(/* center */98248149),
            /* :: */[
              funFactText,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var funFactContainer = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.gridTemplateColumns(/* :: */[
              /* `repeat */[
                108828507,
                /* tuple */[
                  /* autoFit */494053794,
                  /* `minmax */[
                    -754859950,
                    /* tuple */[
                      /* `rem */[
                        5691738,
                        60.0
                      ],
                      /* `fr */[
                        22860,
                        1.0
                      ]
                    ]
                  ]
                ]
              ],
              /* [] */0
            ]),
        /* :: */[
          Css.alignItems(/* start */67859554),
          /* :: */[
            Css.marginLeft(/* `rem */[
                  5691738,
                  5.0
                ]),
            /* :: */[
              funFactText,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var funFactImage = Css.style(/* :: */[
      Css.marginTop(/* `rem */[
            5691738,
            2.0
          ]),
      /* :: */[
        Css.width(/* `rem */[
              5691738,
              30.0
            ]),
        /* :: */[
          Css.height(/* `rem */[
                5691738,
                20.0
              ]),
          /* [] */0
        ]
      ]
    ]);

var Style = /* module */[
  /* funFactText */funFactText,
  /* titleContainer */titleContainer,
  /* funFactContainer */funFactContainer,
  /* funFactImage */funFactImage
];

function s(s$1) {
  return s$1;
}

function Funfacts(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: titleContainer
                }, React.createElement(Section$Website.make, {
                      title: "Some fun facts about my hobbies",
                      children: React.createElement("p", undefined, "While you're here on this website, might as well learn a few fun facts that I find interesting!")
                    })), React.createElement("div", {
                  className: funFactContainer
                }, React.createElement(Section$Website.make, {
                      title: "Olympic Weightlifting",
                      children: null
                    }, React.createElement("p", undefined, "Olympic Weightlifting  made its first appearence in the ", React.createElement("a", {
                              href: "https://www.olympic.org/athens-1896"
                            }, "1896 Olympics"), " and then again in", React.createElement("a", {
                              href: "https://www.olympic.org/st-louis-1904"
                            }, " 1904"), " however, it wasn't until ", React.createElement("a", {
                              href: "https://www.olympic.org/antwerp-1920"
                            }, "1920"), " that it was permanently established as an Olympic Sport."), React.createElement("img", {
                          className: funFactImage,
                          src: "static/gifs/oly.gif"
                        })), React.createElement(Section$Website.make, {
                      title: "Programming",
                      children: null
                    }, React.createElement("p", undefined, React.createElement("a", {
                              href: "https://en.wikipedia.org/wiki/Grace_Hopper"
                            }, "Grace Murray Hopper "), "was one of the first computer programmers to work on the Harvard Mark I.\n             She was also a United States Navy rear admiral, helped develop ", React.createElement("a", {
                              href: "https://en.wikipedia.org/wiki/COBOL"
                            }, "COBOL "), "-- one of the first high-level\n             programming languages -- and invented the first compiler, a program that translates programming code\n             to machine language."), React.createElement("img", {
                          className: funFactImage,
                          src: "static/images/gracehopper.jpg"
                        })), React.createElement(Section$Website.make, {
                      title: "Web Development",
                      children: null
                    }, React.createElement("p", undefined, "This website was built with", React.createElement("a", {
                              href: "https://reasonml.github.io/"
                            }, " Reason "), " and ", React.createElement("a", {
                              href: "https://nextjs.org/"
                            }, "Next.js."), " ReasonML is a syntax extension for the OCaml language created by Facebook.\n             Rather than creating an entirely new language, the creators of Reason chose to\n             build on top of OCaml, a battle-tested functional systems programming language\n             that's been around since the late 1990s."), React.createElement("img", {
                          className: funFactImage,
                          src: "static/images/reason.png"
                        })), React.createElement(Section$Website.make, {
                      title: "BJJ",
                      children: null
                    }, React.createElement("p", undefined, "Brazilian Jiu Jitsu is a relatively new martial art, originating from Rio de Jeneiro in the 1920s. Nowadays, it takes an average\n        of 8-12 years to get a black belt in the sport and is practiced by many around the world. There is never an age\n        that is too old to start!"), React.createElement("img", {
                          className: funFactImage,
                          src: "static/images/bjj.jpg"
                        }))));
}

var make = Funfacts;

var $$default = Funfacts;

export {
  Style ,
  s ,
  make ,
  $$default ,
  $$default as default,
  
}
/* funFactText Not a pure module */
