// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Icons$MyBlog from "../src/bindings/Icons.bs.js";
import * as Section$MyBlog from "../src/components/layout/Section.bs.js";

var text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sagittis, risus vel mollis interdum, nulla augue aliquet quam";

var funfactsContainer = Css.style(/* :: */[
      Css.display(/* grid */-999565626),
      /* :: */[
        Css.gridTemplateColumns(/* :: */[
              /* `fr */[
                22860,
                1.0
              ],
              /* :: */[
                /* `fr */[
                  22860,
                  1.0
                ],
                /* [] */0
              ]
            ]),
        /* :: */[
          Css.marginLeft(/* `rem */[
                5691738,
                5.0
              ]),
          /* [] */0
        ]
      ]
    ]);

var funFactImage = Css.style(/* :: */[
      Css.width(/* `percent */[
            -119887163,
            80.0
          ]),
      /* :: */[
        Css.height(/* `percent */[
              -119887163,
              80.0
            ]),
        /* [] */0
      ]
    ]);

var Style = /* module */[
  /* funfactsContainer */funfactsContainer,
  /* funFactImage */funFactImage
];

function Funfacts(Props) {
  return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement(Section$MyBlog.make, {
                      title: "Some fun facts about my hobbies!",
                      icon: React.createElement(Icons$MyBlog.Wave[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("p", undefined, text)
                    })), React.createElement("div", {
                  className: funfactsContainer
                }, React.createElement(Section$MyBlog.make, {
                      title: "Olympic Weightlifting",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Wave[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    }), React.createElement(Section$MyBlog.make, {
                      title: "Programming",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    }), React.createElement(Section$MyBlog.make, {
                      title: "Web Development",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    }), React.createElement(Section$MyBlog.make, {
                      title: "BJJ",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    }), React.createElement(Section$MyBlog.make, {
                      title: "Video Games",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    }), React.createElement(Section$MyBlog.make, {
                      title: "Geocaching",
                      subtitle: text,
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("img", {
                            className: funFactImage,
                            src: "static/images/img1.png"
                          })
                    })));
}

var make = Funfacts;

var $$default = Funfacts;

export {
  text ,
  Style ,
  make ,
  $$default ,
  $$default as default,
  
}
/* funfactsContainer Not a pure module */
