// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Icons$MyBlog from "../src/bindings/Icons.bs.js";
import * as Gallery$MyBlog from "../src/components/layout/Gallery.bs.js";
import * as Section$MyBlog from "../src/components/layout/Section.bs.js";

var sectionContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(/* spaceBetween */516682146),
        /* :: */[
          Css.alignItems(/* start */67859554),
          /* [] */0
        ]
      ]
    ]);

var Style = /* module */[/* sectionContainer */sectionContainer];

var firstText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam aliquet turpis quam, id commodo odio accumsan eget. Vivamus ipsum magna, mattis quis ullamcorper nec, vulputate sed neque. Nullam mollis lacinia ex, vel cursus tortor feugiat vitae.";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement(Gallery$MyBlog.make, { }), React.createElement("div", {
                  className: sectionContainer
                }, React.createElement(Section$MyBlog.make, {
                      title: "Hey, I'm Martin - A software developer from Canada",
                      icon: React.createElement(Icons$MyBlog.Wave[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("p", undefined, firstText)
                    }), React.createElement(Section$MyBlog.make, {
                      title: "Development Experience",
                      icon: React.createElement(Icons$MyBlog.Github[/* make */0], {
                            height: "2rem"
                          }),
                      children: React.createElement("p", undefined, firstText)
                    })));
}

var make = Index;

var $$default = Index;

export {
  Style ,
  firstText ,
  make ,
  $$default ,
  $$default as default,
  
}
/* sectionContainer Not a pure module */
