// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Icons$Website from "../src/bindings/Icons.bs.js";
import * as Style$Website from "../src/components/layout/Style.bs.js";
import * as Gallery$Website from "../src/components/layout/Gallery.bs.js";
import * as Section$Website from "../src/components/layout/Section.bs.js";

var indexText = Css.selector("p", /* :: */[
      Css.fontSize(Style$Website.Sizes[/* medium */1]),
      /* [] */0
    ]);

var indexContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.justifyContent(/* spaceBetween */516682146),
        /* :: */[
          Css.flexWrap(/* wrap */-822134326),
          /* :: */[
            Css.alignItems(/* start */67859554),
            /* :: */[
              indexText,
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var Style = /* module */[
  /* indexText */indexText,
  /* indexContainer */indexContainer
];

function s(s$1) {
  return s$1;
}

function Index(Props) {
  return React.createElement("div", undefined, React.createElement(Gallery$Website.make, { }), React.createElement("div", {
                  className: indexContainer
                }, React.createElement(Section$Website.make, {
                      title: "Hey, I'm Martin - A software developer from Canada",
                      icon: React.createElement(Icons$Website.Wave[/* make */0], {
                            height: "4rem"
                          }),
                      children: React.createElement("p", undefined, "I'm a 4th year computer science student at ", React.createElement("a", {
                                href: "https://www.sfu.ca/"
                              }, "Simon Fraser University "), "I've also previously graduated from ", React.createElement("a", {
                                href: "https://www.bcit.ca/"
                              }, "BCIT"), " with a 2 year diploma. I enjoy working with new technologies and being exposed to all kinds of ideas.\n             Feel free to get in touch with me!")
                    }), React.createElement(Section$Website.make, {
                      title: "Development Experience",
                      icon: React.createElement(Icons$Website.Github[/* make */0], {
                            height: "4rem"
                          }),
                      children: React.createElement("p", undefined, "I have experience working with various languages and frameworks.\n             At BCIT, I was exposed to a lot of C++ and networking principles.\n             At SFU, I have taken a more general approach and have taken courses in compiler design and implementation, embedded development,\n             computational complexity, and parallel programming. In my free time, I like to work on web development projects\n             and genuinely enjoy working with React.")
                    })));
}

var make = Index;

var $$default = Index;

export {
  Style ,
  s ,
  make ,
  $$default ,
  $$default as default,
  
}
/* indexText Not a pure module */
