// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Gallery$MyBlog from "../src/components/layout/Gallery.bs.js";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement(Gallery$MyBlog.make, { }));
}

var make = Index;

var $$default = Index;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
